#!/bin/bash

export ARCH=arm
export SUBARCH=arm
export CROSS_COMPILE=arm-linux-gnueabihf-
export PATH=../gcc-linaro/bin/:$PATH
#make untermensch_defconfig
bash
make -j4
cp arch/arm/boot/zImage ../asus_tools/
find ! -path './compat-drivers/*'  -name "*.ko" -exec cp {} ../asus_tools/system/lib/modules/ \;
